### ISSUE TITLE
I wrote a htonl() function that return a number

### ISSUE THREAD

**Issue by hupantingxue** [mattcg/network-byte-order#1]
<pre>
function htonl(n) {
    ret = ((n & 0xFF000000) >>> 24 >>> 0) |
     ((n & 0x00FF0000) >>> 16 << 8 >>> 0) |
     ((n & 0x0000FF00) >>>  8 << 16 >>> 0) |
     ((n & 0x000000FF) >>>  0 << 24 >>> 0);
    return (ret >>> 0);
}
</pre>

**Comment by mattcg** [comment]
Thank you, @hupantingxue. What is the use case?

**Comment by hupantingxue** [comment]
Just the same with the htonl() in other languages, convert values between host and network byte order, return an unsigned interger.

**Comment by mattcg** [comment]
Would you like to turn this into a pull request?

**Comment by hupantingxue** [comment]
OK
